language: generic
services:
  - docker

before_install:
  - docker build -t roger2427/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true roger2427/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app:  "docker-react"
  env:  "DockerReact-env-1"
  bucket_name:  "elasticbeanstalk-us-east-2-464922769542"
  bucket_path:  "docker-react"
  on:
    branch: main
  access_key_id:  $AWS_ACCESS_KEY
  secret_access_key:  $AWS_SECRET_KEY
  