languaje: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - docker build -t kibalion2427/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kibalion2427/docker-react npm run test
