sudo: required
services:
  - docker

before_install:
  - docker build -t kibalion2427/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kibalion2427/docker-react npm run test
  docker run -e CI=true 261e92ec16d7 npm run test

